---
title: MiniVAN
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: MiniVAN, a VNA tool, accessible to scholars with little knowledge of
  mathematics or coding and yet capable to scale up to graphs of several thousands
  of nodes
coverImage: images/MiniVAN_ScreenshotMosaic.gif
coverImageWidth: '2812'
coverImageHeight: '1100'
mainCover: "../images/ScreenshotMosaic.gif"
themeColor: "#7FBDF8"
textColor: 2e2d2e
cookieBgColor: "#000000"
cookieButton: "#7FBDF8"
